---
# CI build for DPTLib
#

name: DPTLib
on: [push]
jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - { name: "Ubuntu build",  os: "ubuntu-latest",  install: "sudo apt-get install cmake ninja-build" }
          - { name: "Windows build", os: "windows-latest", install: "choco install cmake ninja" }
          - { name: "macOS build",   os: "macos-latest",   install: "brew install cmake ninja" }
    steps:
      - uses: actions/checkout@v2
      - run: ${{ matrix.config.install }}
      - run: |
          mkdir build
          cd build
          cmake -GNinja ..
          cmake --build .
